name: アジャラジテスト
description: "アジャイルラジオは、アジャイル開発に関するありとあらゆる情報を取り上げる番組です。毎回、アジャイルにまつわる様々なテーマを掘り下げ、できる限り語り尽くします。"
url: https://matsuoshi.github.io
social:
  email: agileradio@example.com
  github: agileradio
  facebook: AgileRadio
  twitter: agileradio15
author:
  name: アジャイルラジオ
  bio: "アジャイルラジオは、スクラム道関西の協力でお送りしています。"
  email: agileradio@example.com
  image: https://agileradio.github.io/assets/img/agileradio_banner_1400x1400.jpg
  github: agileradio
  facebook: AgileRadio
  twitter: agileradio15
  show_on_post: true
permalink: /:year/:month/:day/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/page/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-gist
#  - jekyll-feed

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - vendor
  - .idea
  - package.json
